version: "3.8"
services:
  backend:
    image: product-react-spring
    ports:
      - "8080:8080"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:80"
    depends_on:
      - backend
